### ISSUE TITLE
LearningSession: System.NullReferenceException

### ISSUE THREAD

**Issue by tj-mai** [MemoWikis/webapp#1166]
LoadspecificQuestion tries to get a step on a null learningsession

examples:
<details>
  <summary>LoadSpecificQuestion</summary>
  
  ### LoadSpecificQuestion Exception
  ```c
System.NullReferenceException: Object reference not set to an instance of an object.
   at LearningSessionStoreController.LoadSpecificQuestion(LoadSpecificQuestionJson json) in /source/TrueOrFalse.Frontend.Web/Views/ApiVueApp/Stores/LearningSessionStoreController.cs:line 148
   at lambda_method689(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at RequestTimingForStaticFilesMiddleware.InvokeAsync(HttpContext context) in /source/TrueOrFalse.Frontend.Web/Middlewares/RequestTimingForStaticFilesMiddleware.cs:line 30
   at TrueOrFalse.Frontend.Web.Middlewares.AutoLoginMiddleware.InvokeAsync(HttpContext httpContext) in /source/TrueOrFalse.Frontend.Web/Middlewares/AutoLoginMiddleware.cs:line 56
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at TrueOrFalse.Frontend.Web.Middlewares.ErrorHandlerMiddleware.InvokeAsync(HttpContext httpContext) in /source/TrueOrFalse.Frontend.Web/Middlewares/ErrorHandlerMiddleware.cs:line 19
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
  ```
</details>

<details>
  <summary>LearningSessionCreator</summary>
  
  ### LearningSessionCreator
  ```c
System.NullReferenceException: Object reference not set to an instance of an object.
   at LearningSessionCreator.GetStep(Int32 index) in /source/TrueOrFalse/Domain/Knowledge/Learning/LearningSessionNew/Ops/LearningSessionCreator.cs:line 177
   at LearningSessionStoreController.LoadSpecificQuestion(LoadSpecificQuestionJson json) in /source/TrueOrFalse.Frontend.Web/Views/ApiVueApp/Stores/LearningSessionStoreController.cs:line 148
   at lambda_method689(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at RequestTimingForStaticFilesMiddleware.InvokeAsync(HttpContext context) in /source/TrueOrFalse.Frontend.Web/Middlewares/RequestTimingForStaticFilesMiddleware.cs:line 30
   at TrueOrFalse.Frontend.Web.Middlewares.AutoLoginMiddleware.InvokeAsync(HttpContext httpContext) in /source/TrueOrFalse.Frontend.Web/Middlewares/AutoLoginMiddleware.cs:line 56
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at TrueOrFalse.Frontend.Web.Middlewares.ErrorHandlerMiddleware.InvokeAsync(HttpContext httpContext) in /source/TrueOrFalse.Frontend.Web/Middlewares/ErrorHandlerMiddleware.cs:line 19
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
  ```
</details>

<details>
  <summary>SendAnswerToLearningSession</summary>
  
  ### SendAnswerToLearningSession
  ```c
System.NullReferenceException: Object reference not set to an instance of an object.
   at AnswerBodyController.GetLearningResult(Int32 id, Guid questionViewGuid, String answer, Boolean isTestMode) in /source/TrueOrFalse.Frontend.Web/Views/ApiVueApp/Components/Question/AnswerBody/AnswerBodyController.cs:line 113
   at lambda_method697(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at RequestTimingForStaticFilesMiddleware.InvokeAsync(HttpContext context) in /source/TrueOrFalse.Frontend.Web/Middlewares/RequestTimingForStaticFilesMiddleware.cs:line 30
   at TrueOrFalse.Frontend.Web.Middlewares.AutoLoginMiddleware.InvokeAsync(HttpContext httpContext) in /source/TrueOrFalse.Frontend.Web/Middlewares/AutoLoginMiddleware.cs:line 56
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at TrueOrFalse.Frontend.Web.Middlewares.ErrorHandlerMiddleware.InvokeAsync(HttpContext httpContext) in /source/TrueOrFalse.Frontend.Web/Middlewares/ErrorHandlerMiddleware.cs:line 19
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
  ```
</details>

**Comment by tj-mai** [comment]
last 7d:
36x LoadSpecificQuestion
7x LearningSessionCreator
0x SendAnswerToLearningSession
